import { getCustomer } from "@/api/services/customer-service";
import { AppSidebar } from "@/components/app-sidebar/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/toaster";
import { CustomerProvider } from "@/hooks/use-customer";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import "./globals.css";
import { Customer } from "@/api/types/customer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const customerId = (await cookies()).get("customerId")?.value;
  const customer: Customer | null =
    customerId != undefined ? (await getCustomer(customerId)).data : null;

  return (
    <html lang="en">
      <body>
        <CustomerProvider customer={customer}>
          <SidebarProvider>
            <AppSidebar hasCustomerId={customerId != undefined} />
            <main className="p-4 w-full">
              <SidebarTrigger className="absolute" />
              {children}
              <Toaster />
            </main>
          </SidebarProvider>
        </CustomerProvider>
      </body>
    </html>
  );
}
